# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5e64c6f7bd14cf9081bcdcf9686a886e899110184d29df5227f0abc1cd6496bf54dfcac1c6ccbb2ff22cfd5f2bddb15d3756a158ab79fc7a52768bcefe04fb4

test:
  secret_key_base: 863a1f46102b2b2383ebca660abf73cdd663b96c78fda61b35739b57b39f48b5622ab67f9af8382c7e32d5b1187858aecf2bc5ca8e1576b2b3b84d5fc8dd9530

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
